### PR TITLE
Update chat_commands.py

### PR DESCRIPTION
**Pull request by LDMBatman**
Added callback = None for Rcon.broadcast

### CODE REVIEW

**Comment by f4ble** [comment]
Why specify None? 

Lang.get() defaults to "Generic" section without having to specify None. Did I miss something?

**Comment by LDMBatman** [comment]
In my mind when whe call Rcon.broadcast("Text",Rcon.response_callback_response_only), nothing happens.

I don't know if it works with ommited callback argument but I specified None for each Rcon.broadcast() method in my prod server.

**Comment by f4ble** [comment]
Ah yes! broadcast needs a callback.

**Comment by f4ble** [comment]
I have fixed this in my latest commit. Added a proper callback.

**Pull request closed without merging**
